main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^about/$', views.about, name="about"),
    url(r'^thanks/$', views.thanks, name="thanks"),
    url(r'^contact/$', views.ContactView, name="contact"),
    url(r'^customer_list/$', views.CustomerList, name="customer_list"),
    url(r'^(?P<pk>[0-9]+)/$', views.CustomerDetail, name='customer_detail'),
    url(r'^create/$', views.CustomerCreate, name='customer_create'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.CustomerUpdate, name='customer_edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.CustomerDelete, name='customer_delete'),
]

sup_world/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main.views import ContactView
from main.views import CustomerList
from main.views import CustomerDetail
from main.views import CustomerDelete
from main.views import CustomerCreate
from main.views import CustomerUpdate
import sup_world.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^contact/', ContactView.as_view()),
    url(r'^customer_list/$', CustomerList.as_view()),
    url(r'^create/$', CustomerCreate.as_view()),
    url(r'^(?P<pk>[0-9]+)/update/$', CustomerUpdate.as_view()),
    url(r'^(?P<pk>[0-9]+)/$', CustomerDetail.as_view()),
    url(r'^(?P<pk>[0-9]+)/delete/$', CustomerDelete.as_view()),
    url(r'^', include("main.urls", namespace="main", app_name="main")),
]

main/models.py
from __future__ import unicode_literals
from django.contrib import auth
from django.db import models

class Customer(models.Model):
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	email = models.TextField()
	phone_number = models.IntegerField()

def get_absolute_url(self):
   return reverse('comment_detail', args=[str(self.id)])

main/forms.py
from django import forms
from django.core.mail import send_mail


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=75)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()

    def send_email(self):
        # Write some code for sending an email
        #note that email is directed to console at this moment
        send_mail(self['subject'].value(), self['message'].value(), self['sender'].value(), ['desireedesario@gmail.com'], fail_silently=False)
        return super(ContactForm, self)

main/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from main.models import Customer
from main.forms import ContactForm

def index(request):
    return render(request, "main/index.html")

def about(request):
    return render(request, "main/about.html")

def thanks(request):
    return render(request, "main/thanks.html")

class ContactView(FormView):
    template_name = "main/contact.html"
    form_class = ContactForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # Write code for after form validation
        ContactForm.send_email(form)
        return super(ContactView, self).form_valid(form)

class CustomerList(ListView):
    model = Customer

class CustomerDetail(DetailView):
    model = Customer

class CustomerCreate(CreateView):
    model = Customer
    fields = ['first_name', 'last_name', 'email', 'phone_number']
    success_url = '/customer_list/'

class CustomerUpdate(UpdateView):
    model = Customer
    fields = ['first_name', 'last_name', 'email', 'phone_number']
    success_url = '/customer_list/'

class CustomerDelete(DeleteView):
    model = Customer
    success_url = '/customer_list/'

main/templates/main/about.html
{% extends "main/base.html" %}
{% block content %}
  <h2>About</h2>
  <center>
    <img src="https://s3.amazonaws.com/media-p.slid.es/uploads/395051/images/1978224/django_python.jpg">
    <p style="padding: 7%;">This is my basic Python/Django practice site allowing you to email request on how to better this site and give feedback on what to add. Please enjoy yourself.</p>
  </center>
{% endblock content %}

main/templates/main/base.html
<!DOCTYPE html>
<html>
  <head>
      <title>Sup, World!</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

  <!-- Navbar -->
  <nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand mb-0" href='{% url "main:index" %}'>Customer Requests</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href='{% url "main:index" %}'>Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href='{% url "main:about" %}'>About</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href='{% url "main:contact" %}'>Contact</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href='{% url "main:customer_list" %}'>Customer List</a>
    </li>
    <!-- <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
      <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
  </ul> -->
  <!-- <form class="form-inline float-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form> -->
</nav> <!-- Navbar -->

    <h1>Customer Requests</h1>
    {% block content %}

    {% endblock content %}
  </body>
</html>

main/templates/main/contact.html
{% extends "main/base.html" %}
{% block content %}
  <h2>Contact</h2>
  <div style="margin-left: 20%">
    <div class="form-group">
      <form role="form" action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
      </form>
    </div>
  </div>





{% endblock content %}

main/templates/main/customer_confirm_delete.html
{% extends "main/base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object.first_name }}?</p>
    <input type="submit" value="yes" />
    <a href="{% url 'main:customer_list' %}">no</a>
  </form>
{% endblock %}

main/templates/main/customer_detail.html
{% extends "main/base.html" %}

{% block content %}
  <h2>{{ object.first_name }} {{ object.last_name }}</h2>
  <p><em>by {{ object.email }}</em></p>
  <p>{{ object.phone_number }}</p>
  <a href="{% url 'main:customer_edit' object.pk %}">Edit</a>
  |
  <a href="{% url 'main:customer_delete' object.pk %}">Delete</a>
{% endblock %}

main/templates/main/customer_form.html
{% extends "main/base.html" %}

{% block content %}
  {% if object %}
    <h2>Edit {{ object.first_name }}</h2>
  {% else %}
    <h2>Create</h2>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" />
  </form>
{% endblock %}

main/templates/main/customer_list.html
{% extends "main/base.html" %}

{% block content %}
  {% for customer in object_list %}
  <div style="margin-left: 10%">
    <h4>
      {{ customer.first_name }} {{ customer.last_name }}
      <a href="{% url 'main:customer_detail' customer.pk %}">detail...</a>
    </h4>
  {% endfor %}
  <a href="{% url 'main:customer_create' %}">Add...</a>
</div>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block content %}
  <h2>Hello, Customers!</h2>
  <p>
    This is a basic project in Django and Python allowing you to fill in customer requests and connect with others. Things you may be able to do:
  </p>
    <ul class="list-group" style="width:50%;margin: 0 auto;">
      <li class="list-group-item">Email in a client request!</li>
      <li class="list-group-item">Edit your request in our database.</li>
      <li class="list-group-item">Cancel in the request at any given moment of time.</li>
    </ul>
{% endblock content %}

main/templates/main/navigation.html
<nav>
  <ul>
    <li><a href='{% url "main:index" %}'>Home</a></li>
    <li><a href='{% url "main:about" %}'>About</a></li>
    <li><a href='{% url "main:contact" %}'>Contact</a></li>
    <li><a href='{% url "main:customer_list" %}'>Customer List</a></li>
  </ul>
</nav>

main/templates/main/thanks.html
{% extends "main/base.html" %}
{% block content %}
  <h2>Thanks!</h2>
{% endblock content %}